// Generated by CoffeeScript 2.2.2
var a, aa, abc;

a = function(a, b) {
  a + b;
  return a + 2 * b;
};

console.log(a(5, 4));

aa = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20];

abc = (function() {
  var constructor;

  class abc {};

  constructor = function() {
    this.prop = 3;
    this.prop = 4;
    return void 0;
  };

  return abc;

}).call(this);

//# sourceMappingURL=test.js.map
